DROP TABLE IF EXISTS shift;
CREATE TABLE shift (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    employee_id BIGINT NOT NULL,
    date DATE NOT NULL,
    type ENUM('MORNING', 'NIGHT') NOT NULL DEFAULT 'MORNING',
    FOREIGN KEY (employee_id) REFERENCES User(id)
);